[build]
  command = "npm run build"
  publish = "dist"

[forms]
  [forms.contact]
    name = "Contact Form"
    fields = [
      { name = "name", label = "Name", widget = "string", required = true },
      { name = "email", label = "Email", widget = "email", required = true },
      { name = "message", label = "Message", widget = "text", required = true }
    ]
