[build]
  command = "npm run build"
  publish = "dist"

[forms]
  [forms.contact]
    name = "Contact Form"
    fields = [
      { name = "name", label = "Name", widget = "string", required = true },
      { name = "email", label = "Email", widget = "email", required = true },
      { name = "message", label = "Message", widget = "text", required = true }
    ]

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special case for /test path to allow both React route and static HTML
[[redirects]]
  from = "/test"
  to = "/test.html"
  status = 200
